---
booktitle: Proceedings of the Workshop on Statistically Sound Data Mining at ECML/PKDD
volume: 47
year: '2014'
shortname: SSDM
start: 2014-09-15
end: 2014-09-15
published: 2015-11-27
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: SSDM-2014
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Wilhelmiina
  family: Hämäläinen
- given: François
  family: Petitjean
- given: I.
  family: Webb
description: |
  Proceedings of the Workshop on Statistically Sound Data Mining at ECML/PKDD
    Held in Nancy, France on 15 September 2014

  Published as Volume 47 by the Proceedings of Machine Learning Research on 27 November 2015.

  Volume Edited by:
    Wilhelmiina Hämäläinen
    François Petitjean
    I. Webb

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 15 Sep
url: http://proceedings.mlr.press
baseurl: "/v47"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v47
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Statistically Sound Data Mining
  url: http://cs.joensuu.fi/pages/whamalai/SSDM/ssdm14.html
  location: Nancy, France
  dates:
  - 2014-09-15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v47.bib
